version: 2
enable-beta-ecosystems: true

updates:
- package-ecosystem: "bundler"
  directory: "/"
  versioning-strategy: increase
  insecure-external-code-execution: deny
  allow:
    - dependency-type: "all"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: "America/New_York"    
